version: 2
jobs:
  deploy:
    working_directory: ~/app
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: apk add --no-cache nodejs npm yarn
      - run: yarn
      - run: yarn build
      - run: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: gcloud app deploy --quiet --project nenecchi-work

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
